data:
  dataset_handle: "samuelcortinhas/sports-balls-multiclass-image-classification"
  download_dir: "./data/raw_data"
  batch_size: 64
  num_workers: 4
  train_split_ratio: 0.8
  seed: 42

model:
  name: "mobilenet"
  width_mult: 1.0

train:
  epochs: 40
  learning_rate: 0.001   
  device: "cuda"
  checkpoint_dir: "./checkpoints"